# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('slug', models.SlugField(blank=True)),
                ('type_of_file', models.CharField(blank=True, max_length=50)),
                ('path_of_file', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=250)),
                ('last_folder', models.BooleanField(default=True)),
                ('folder_pointing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='ekfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Folder'),
        ),
    ]
