# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170729_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=polls.models.item_upload_to),
        ),
    ]
