# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170729_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekfile',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
